import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Join Me!",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

// The root layout is the outermost component that wraps all pages
// this prevents us from having to repeat the same layout code in every page
// it also prevents us from loading redundant javascript in every page
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* this applies the font to the whole page */}
      <body>
        <div>
          {/* <Header /> */}
          {/* <main className="flex min-h-screen w-full"> */}
          {/* <main> */}
          {/* <Separator orientation="vertical" /> */}
          {children}
          {/* <Separator orientation="vertical" /> */}
          {/* </main> */}
        </div>
      </body>
    </html>
  );
}
